create extension if not exists pgcrypto;
create table if not exists public.profiles(id uuid primary key references auth.users(id) on delete cascade,full_name text,role text not null default 'citizen' check(role in('citizen','admin')),created_at timestamptz not null default now());
create table if not exists public.services(id uuid primary key default gen_random_uuid(),name text not null,slug text unique not null,description text not null,category text not null,requirements jsonb not null default '[]'::jsonb,is_active boolean not null default true,created_at timestamptz not null default now());
create table if not exists public.applications(id uuid primary key default gen_random_uuid(),application_number text unique not null,user_id uuid not null references auth.users(id) on delete cascade,service_id uuid references public.services(id),status text not null default 'submitted' check(status in('draft','submitted','verified','certificate_issued','rejected')),citizen_data jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.documents(id uuid primary key default gen_random_uuid(),application_id uuid not null references public.applications(id) on delete cascade,user_id uuid not null references auth.users(id) on delete cascade,document_type text not null,file_name text not null,file_path text not null,status text not null default 'uploaded',created_at timestamptz not null default now());
create table if not exists public.agent_events(id uuid primary key default gen_random_uuid(),application_id uuid not null references public.applications(id) on delete cascade,event_type text not null,message text not null,status text not null default 'completed',created_at timestamptz not null default now());
insert into public.services(name,slug,description,category,requirements) values('Income Certificate','income-certificate','Apply for an income certificate through an AI-assisted citizen workflow.','Certificates','["Aadhaar / ID proof","Address proof","Income proof"]'),('Pension Scheme','pension','Explore pension application requirements and start an assisted application.','Social Welfare','["Identity proof","Bank details","Age proof"]'),('Scholarship','scholarship','Find scholarship information and prepare the required application details.','Education','["Identity proof","Student ID","Income proof","Academic record"]'),('E-Kalyan Scholarship','e-kalyan-scholarship','Explore e-Kalyan student scholarship application guidance. Eligibility and requirements vary by state and scholarship programme.','Education','["Identity proof","Domicile / residence proof","Student ID or admission proof","Bank account details","Income or caste certificate, if applicable","Academic records"]'),('Birth Certificate','birth-certificate','Request birth certificate assistance and document guidance.','Certificates','["Identity proof","Birth record / hospital proof"]'),('Caste Certificate','caste-certificate','Prepare a caste certificate application with document guidance.','Certificates','["Identity proof","Address proof","Supporting caste document"]') on conflict(slug) do nothing;
alter table public.profiles enable row level security;alter table public.services enable row level security;alter table public.applications enable row level security;alter table public.documents enable row level security;alter table public.agent_events enable row level security;
create policy "public read active services" on public.services for select using(is_active=true);
create policy "users read own applications" on public.applications for select using(auth.uid()=user_id);create policy "users insert own applications" on public.applications for insert with check(auth.uid()=user_id);
create policy "users read own documents" on public.documents for select using(auth.uid()=user_id);create policy "users insert own documents" on public.documents for insert with check(auth.uid()=user_id);
create policy "users read own events" on public.agent_events for select using(exists(select 1 from public.applications a where a.id=application_id and a.user_id=auth.uid()));
-- Create a PRIVATE Storage bucket named documents.
-- After creating an admin Auth user, run:
-- insert into public.profiles(id,full_name,role) values('YOUR_AUTH_USER_UUID','Hackathon Admin','admin') on conflict(id) do update set role='admin';
